name: depth_benchmark
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - aiofiles==24.1.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - brotli==1.2.0
      - certifi==2026.1.4
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - depth-benchmark==0.1.0
      - exceptiongroup==1.3.1
      - fastapi==0.128.0
      - ffmpy==1.0.0
      - filelock==3.20.0
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - glcontext==3.0.0
      - gradio==6.3.0
      - gradio-client==2.0.3
      - groovy==0.1.2
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.2
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - moderngl==5.12.0
      - moge==2.0.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - opencv-python==4.12.0.88
      - orjson==3.11.5
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pipeline==1.0.0
      - protobuf==6.33.4
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.21
      - pytz==2025.2
      - pyyaml==6.0.3
      - rich==14.2.0
      - safehttpx==0.1.7
      - scipy==1.15.3
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - six==1.17.0
      - starlette==0.50.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tomlkit==0.13.3
      - torch==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - tqdm==4.67.1
      - trimesh==4.11.0
      - triton==3.3.1
      - typer==0.21.1
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - utils3d==1.3
      - uvicorn==0.40.0
      - werkzeug==3.1.5
